name: smart_media_widgets
description: "A Flutter package providing smart, reusable widgets for displaying images and videos with preloading, error handling, and optimization features."
version: 0.1.0-dev.1
homepage: https://github.com/Gperez88/smart_media_widgets
license: MIT

environment:
  sdk: ^3.8.1
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  video_player: ^2.10.0
  chewie: ^1.11.3
  path_provider: ^2.1.5
  http: ^1.4.0
  audio_waveforms: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: 